// Auto-generated by generate-config.js. Do not edit manually.
// Contains only public Supabase runtime values that are safe to expose.
window.__SUPABASE_URL = 'https://ifycpxtpyysuthnknptl.supabase.co'
window.__SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeWNweHRweXlzdXRobmtucHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NzAwMDksImV4cCI6MjA4NjA0NjAwOX0.RO2F6bLvbo34ZGRDpjbv8NrsHtmkX_D9mtXTVb0ErhY';
