// generate-config.js
// Reads .env file (local dev) or process.env (Vercel) and writes Frontend/js/env.js + config.js

const fs = require('fs');
const path = require('path');

// Try reading .env file; fall back to process.env (for Vercel / CI)
const envPath = path.join(__dirname, '..', '.env');
const env = {};

if (fs.existsSync(envPath)) {
  console.log('📄 Reading from .env file');
  fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    const match = line.match(/^\s*([\w]+)\s*=\s*["']?(.+?)["']?\s*$/);
    if (match) env[match[1]] = match[2];
  });
} else {
  console.log('☁️  No .env file found — reading from environment variables (Vercel/CI)');
}

// Env vars from file override, but fall back to process.env
const url = env.SUPABASE_URL || process.env.SUPABASE_URL;
const key = env.SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('❌ SUPABASE_URL and SUPABASE_ANON_KEY must be set (in .env or environment variables)');
  process.exit(1);
}

// Write env.js (used by supabase-client.js via window globals)
const envContent = `// Auto-generated by generate-config.js. Do not edit manually.
// Contains only the public anon key (safe to expose).
window.__SUPABASE_URL = '${url}'
window.__SUPABASE_ANON_KEY = '${key}';
`;

const envOutPath = path.join(__dirname, '..', 'Frontend', 'js', 'env.js');
fs.writeFileSync(envOutPath, envContent);
console.log('✅ Frontend/js/env.js generated from .env');

// Write config.js (Gemini key/model etc.)
const geminiKey = env.GEMINI_API_KEY || process.env.GEMINI_API_KEY || '';
const geminiModel = env.GEMINI_MODEL || process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const configContent = `// AUTO-GENERATED — do not edit, do not commit
// Run "npm run config" to regenerate from .env
GEMINI_API_KEY = "${geminiKey}";
GEMINI_MODEL = "${geminiModel}";
`;

const outPath = path.join(__dirname, '..', 'Frontend', 'js', 'config.js');
fs.writeFileSync(outPath, configContent);
console.log('✅ Frontend/js/config.js generated from .env');
